openapi: 3.1.0
info:
  version: v1
  title: api-greetings-marco
servers:
  - url: https://pre-api.cloudappi.net/api-template/v1
    description: Development server
  - url: https://api.cloudappi.net/api-template/v1
    description: Production server
tags:
  - name: Greetings
    description: 'operations greetings '
paths:
  /greetings:
    x-apigen-binding:
      model: Greeting
    get:
      summary: get all greetings by user
      operationId: getGreetings
      tags:
        - Greetings
      parameters:
        - $ref: '#/components/parameters/init_param'
        - $ref: '#/components/parameters/limit_param'
        - $ref: '#/components/parameters/total_param'
        - $ref: '#/components/parameters/select_param'
        - $ref: '#/components/parameters/exclude_param'
        - $ref: '#/components/parameters/expand_param'
      security:
        - ApiKeyAuth: []
      responses:
        '206':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/standard_response_greetings'
              examples:
                Ejemplo:
                  $ref: '#/components/examples/get_greetings_response_example'
          '200':
            description: Ok
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/standard_response_greetings'
                examples:
                  Ejemplo:
                    $ref: '#/components/examples/get_greetings_response_example'
          '202':
            description: Accepted
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/standard_response_greetings'
                examples:
                  Ejemplo:
                    $ref: '#/components/examples/get_greetings_response_example'
    post:
      summary: create a greeting
      operationId: createGreeting
      tags:
        - Greetings
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/greeting'
            examples:
              Ejemplo:
                $ref: '#/components/examples/greeting_example'
      responses:
        '201':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/standard_response_greeting'
              example:
                Ejemplo:
                  $ref: '#/components/examples/post_patient_response_example'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/standard_response_greeting'
              examples:
                Ejemplo:
                  $ref: '#/components/examples/client_bad_request_response_example'
  /greetings/search:
    x-apigen-binding:
      model: Patient
    post:
      summary: search a greeting
      operationId: searchGreeting
      tags:
        - Greetings
      parameters:
        - $ref: '#/components/parameters/init_param'
        - $ref: '#/components/parameters/limit_param'
        - $ref: '#/components/parameters/total_param'
        - $ref: '#/components/parameters/select_param'
        - $ref: '#/components/parameters/exclude_param'
        - $ref: '#/components/parameters/expand_param'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/standard_search'
      responses:
        '206':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/standard_response_greetings'
  /greetings/{id}:
    x-apigen-binding:
      model: Greeting
    get:
      summary: get a greeting by id
      operationId: getGreetingById
      tags:
        - Greetings
      parameters:
        - $ref: '#/components/parameters/string_id_param'
        - $ref: '#/components/parameters/select_param'
        - $ref: '#/components/parameters/exclude_param'
        - $ref: '#/components/parameters/expand_param'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/standard_response_greeting'
              examples:
                Ejemplo:
                  $ref: '#/components/examples/greeting_example'
        '404':
          description: Not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/standard_response_greeting'
              examples:
                Ejemplo:
                  $ref: '#/components/examples/standard_not_found_response_example'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/standard_response_greeting'
              examples:
                InternalServerErrorExample:
                  value:
                    result:
                      status: false
                      http_code: 500
                      info: Internal Server Error
                      trace_id: b8240028-8df4-4019-8b03-182a0a9bc88d
                    errors:
                      - code: 1001
                        description: "An unexpected error occurred on the server."
    patch:
      summary: update a Greeting
      operationId: updateGreeting
      tags:
        - Greetings
      parameters:
        - $ref: '#/components/parameters/string_id_param'
        - $ref: '#/components/parameters/limit_param'
        - name: search
          in: query
          required: false
          schema:
            type: string
          description: A search string to filter results.
        - name: page
          in: query
          required: false
          schema:
            type: integer
          description: Page number for pagination.
        - name: per_page
          in: query
          required: false
          schema:
            type: integer
          description: Number of results per page for pagination.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/greeting'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/standard_response_greeting'
    delete:
      summary: delete a greeting by id
      operationId: deleteGreeting
      tags:
        - Greetings
      parameters:
        - $ref: '#/components/parameters/string_id_param'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/standard_response_greeting'
components:
  parameters:
    string_id_param:
      name: id
      in: path
      required: true
      schema:
        type: string
    init_param:
      in: query
      name: $init
      schema:
        type: integer
        format: int
        minimum: 0
        maximum: 1000
        default: 0
      example: 100
    limit_param:
      in: query
      name: $limit
      schema:
        type: integer
        format: int32
    total_param:
      in: query
      name: $total
      schema:
        type: boolean
    select_param:
      in: query
      name: $select
      schema:
        type: array
        items:
          type: string
    exclude_param:
      in: query
      name: $exclude
      schema:
        type: array
        items:
          type: string
    expand_param:
      in: query
      name: $expand
      schema:
        type: array
        items:
          type: string
  schemas:
    standard_response_result:
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/standard_error'
    standard_error:
      type: object
      properties:
        code:
          type: integer
          example: 1003
        description:
          type: string
          example: description of error. Please, don't show it in production
    standard_search:
      type: object
      properties:
        operation:
          type: string
          enum:
            - AND
            - OR
            - GT
            - LT
            - GTEQ
            - LTEQ
            - EQ
            - NEQ
            - IN
            - BETWEEN
            - SUBSTRING
            - LIKE
            - ILIKE
            - NLIKE
            - REGEXP
        values:
          type: array
          items:
            type: object
            properties:
              property:
                type: string
              value:
                type: string
              values:
                type: array
                items:
                  type: string
    standard_response_greetings:
      allOf:
        - $ref: '#/components/schemas/standard_response_result'
        - type: object
          properties:
            data:
              type: array
              items:
                $ref: '#/components/schemas/greeting'
    standard_response_greeting:
      allOf:
        - $ref: '#/components/schemas/standard_response_result'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/greeting'
    standard_response_stays:
      allOf:
        - $ref: '#/components/schemas/standard_response_result'
        - type: object
          properties:
            data:
              type: object
              properties:
                stays:
                  type: array
                  items:
                    $ref: '#/components/schemas/greeting'
    standard_response_stay:
      allOf:
        - $ref: '#/components/schemas/standard_response_result'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/greeting'
    standard_response_rooms:
      allOf:
        - $ref: '#/components/schemas/standard_response_result'
        - type: object
          properties:
            data:
              type: object
              properties:
                rooms:
                  type: array
                  items:
                    $ref: '#/components/schemas/greeting'
    standard_response_room:
      allOf:
        - $ref: '#/components/schemas/standard_response_result'
        - type: object
          properties:
            data:
              $ref: '#/components/schemas/greeting'
    greeting:
      x-apigen-mapping:
        model: Greeting
      type: object
      required:
        - template
        - language
        - channelType
        - greetingType
        - channelData
      properties:
        channelType:
          type: string
          minLength: 3
          maxLength: 5
          enum:
            - email
            - sms
          example: email
          default: email
        language:
          type: string
          description: language for greeting. View ISO 6391
          example: es-ES
          minLength: 2
          maxLength: 6
        greetingType:
          type: string
          description: greeting Type. use api-config to get all greetings types.
          example: happyNewYear
          minLength: 3
          maxLength: 20
        greetingTemplate:
          type: string
          description: greeting Template. use api-config to get all greetings templates.
          example: greenHappyNewYearTemplate
          minLength: 3
          maxLength: 50
        channelData:
          type: string
          description: >-
            data depends on channel type. If channel type is email, the channel
            data would be "marco.sanz@cloudappi.net". If the channel data is
            sms, would be +34658893443
          example: marco.sanz@cloudappi.net".
          minLength: 6
          maxLength: 100
        creationDate:
          type: string
          format: date-time
          description: datetime when the greeting was sent
          example: 20220901T15:54:00Z
          readOnly: true
  examples:
    post_patient_response_example:
      value:
        result:
          status: true
          http_code: 201
          info: Created
          trace_id: b8240028-8df4-4019-8b03-182a0a9bc88d
        data:
          id: 6152f5065e6a5d0530211f77
          name: John
          surname: Doe
    get_greetings_response_example:
      value:
        data:
          - language: es-ES
            channelType: email
            channelData: pedro@yopmail.com
            template: greenHappyNewYearTemplate
            greetingType: happyNewYear
            creationDate: 20220901T15:54:00Z
          - language: es-CO
            channelType: email
            channelData: andres@yopmail.com
            template: greenHappyNewYearTemplate
            greetingType: happyNewYear
            creationDate: 20220901T12:53:00Z
    greeting_example:
      value:
        language: es-ES
        channelType: email
        channelData: pedro@yopmail.com
        template: greenHappyNewYearTemplate
        greetingType: happyNewYear
        creationDate: 20220901T15:54:00Z
    standard_not_found_response_example:
      value:
        result:
          status: false
          http_code: 404
          info: Not found
          trace_id: b8240028-8df4-4019-8b03-182a0a9bc88d
          errors:
            - code: 1104
              message: >-
                No item was found with the identifier provided. Please review:%
                s
    client_bad_request_response_example:
      value:
        result:
          status: false
          http_code: 400
          info: Bad Request
          trace_id: b8240028-8df4-4019-8b03-182a0a9bc88d
          errors:
            - code: 1000
              message: Attribute '% s' cannot contain a null value
  x-apigen-models:
    Patient:
      relational-persistence:
        table: patients
      attributes:
        - name: id
          type: String
          relational-persistence:
            primary-key: true
            autogenerated: true
        - name: name
          type: String
          validations:
            - type: NotEmpty
        - name: surname
          type: String
          validations:
            - type: NotEmpty
        - name: stays
          type: Array
          items-type: Stay
          relational-persistence:
            foreign-column: patient_id
    Stay:
      relational-persistence:
        table: stays
      attributes:
        - name: id
          type: String
          relational-persistence:
            primary-key: true
            autogenerated: true
        - name: cause
          type: String
          validations:
            - type: NotEmpty
        - name: entryDate
          type: LocalDate
          validations:
            - type: NotNull
        - name: dischargeDate
          type: LocalDate
        - name: room
          type: Room
          relational-persistence:
            column: room_id
        - name: patient
          type: Patient
          relational-persistence:
            column: patient_id
    Room:
      relational-persistence:
        table: rooms
      attributes:
        - name: id
          type: String
          relational-persistence:
            primary-key: true
            autogenerated: true
        - name: code
          type: String
          validations:
            - type: NotEmpty
        - name: active
          type: Boolean
        - name: stays
          type: Array
          items-type: Stay
          relational-persistence:
            foreign-column: room_id
x-apigen-project:
  name: Apigen Demo Hospital
  description: Apigen Demo Hospital API
  version: 1.0.0
  java-properties:
    group-id: org.apiaddicts.apitools.apigen.demo
    artifact-id: hospital
